In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.8145e-36,  4.5733e-41, -1.8145e-36],
        [ 4.5733e-41,         nan,  6.8292e+22],
        [ 7.6194e+31,  1.5564e+28,  1.8484e+31],
        [ 1.8370e+25,  1.4603e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1318, 0.3295, 0.6425],
        [0.9532, 0.6244, 0.4758],
        [0.8553, 0.3901, 0.9816],
        [0.5866, 0.1875, 0.8875],
        [0.1957, 0.2444, 0.4327]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4365,  0.7259, -0.9510],
        [ 0.8669, -0.2178, -0.4633],
        [ 0.0733, -0.7413,  0.9654],
        [-0.2675, -1.0458, -0.3628],
        [ 0.2181, -0.1026, -0.6475]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1177,  0.9831,  0.0415],
        [ 1.0822,  0.0820, -0.4256],
        [ 0.5123,  0.2557,  1.8609],
        [-0.0064, -0.7750, -0.2511],
        [ 0.2628,  0.3778, -0.2486]])


In [12]:
print(torch.add(x, y))

tensor([[ 1.1177,  0.9831,  0.0415],
        [ 1.0822,  0.0820, -0.4256],
        [ 0.5123,  0.2557,  1.8609],
        [-0.0064, -0.7750, -0.2511],
        [ 0.2628,  0.3778, -0.2486]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1177,  0.9831,  0.0415],
        [ 1.0822,  0.0820, -0.4256],
        [ 0.5123,  0.2557,  1.8609],
        [-0.0064, -0.7750, -0.2511],
        [ 0.2628,  0.3778, -0.2486]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1177,  0.9831,  0.0415],
        [ 1.0822,  0.0820, -0.4256],
        [ 0.5123,  0.2557,  1.8609],
        [-0.0064, -0.7750, -0.2511],
        [ 0.2628,  0.3778, -0.2486]])


In [15]:
print(x[:, 1])

tensor([ 0.7259, -0.2178, -0.7413, -1.0458, -0.1026])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2211])
0.22108353674411774
